# Generated by Django 5.0.1 on 2024-01-25 15:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('health', models.IntegerField(default=100, verbose_name='HP')),
                ('attack', models.IntegerField(default=5, verbose_name='ATTACK')),
                ('defence', models.IntegerField(default=3, verbose_name='ARMOR')),
                ('agility', models.IntegerField(default=1, verbose_name='AGILITY')),
                ('strength', models.IntegerField(default=1, verbose_name='STRENGTH')),
                ('upgrade_points', models.PositiveIntegerField(default=0, verbose_name='UPGRADE POINTS')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to='img/', verbose_name='IMG')),
                ('balance', models.DecimalField(decimal_places=0, default=100, max_digits=10, verbose_name='MONEY')),
                ('lvl', models.IntegerField(default=1, verbose_name='LEVEL')),
                ('exp', models.IntegerField(default=0, verbose_name='EXP')),
                ('role', models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='ROLE')),
                ('current_position', models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='POSITION IN THE GAME')),
                ('is_fight', models.BooleanField(default=False, verbose_name='IS FIGHT')),
                ('armor_equiped', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_armor_user', to='game.armor', verbose_name='ARMOR')),
                ('dungeon', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.dungeonlvl')),
                ('enemy', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.enemy', verbose_name='ENEMY')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('weapon2_equiped', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon2_user', to='game.weapon', verbose_name='SEC WEAPON')),
                ('weapon_equiped', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon_user', to='game.weapon', verbose_name='WEAPON')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
