# Generated by Django 5.0.1 on 2024-01-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='current_position',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='POSITION IN THE GAME'),
        ),
    ]
