# Generated by Django 5.0.1 on 2024-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='img/', verbose_name='IMG'),
        ),
    ]
