# Generated by Django 5.0.1 on 2024-01-22 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ARMOR NAME')),
                ('img', models.ImageField(upload_to='armor', verbose_name='IMG')),
                ('armor', models.IntegerField(verbose_name='AROMOR+')),
                ('balance', models.IntegerField(verbose_name='SUM')),
                ('lvl', models.IntegerField(verbose_name='LVL')),
                ('dun_lvl', models.IntegerField(verbose_name='DUNGEON LVL')),
            ],
        ),
        migrations.CreateModel(
            name='DungeonLvl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lvl', models.PositiveIntegerField(verbose_name='DUNGEON LVL')),
                ('min_treasure', models.PositiveIntegerField(verbose_name='MIN Treasure')),
                ('max_treasure', models.PositiveIntegerField(verbose_name='MAX Treasure')),
                ('fine', models.PositiveIntegerField(verbose_name='FINE')),
                ('heal', models.PositiveIntegerField(verbose_name='HEAL')),
                ('unlock_lvl', models.PositiveIntegerField(verbose_name='LVL FOR UNLOCK BOSS')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='NAME')),
                ('desc', models.TextField(verbose_name='Desc')),
                ('is_positive', models.BooleanField(default=True, verbose_name='IS_POSITIVE')),
                ('is_church_ef', models.BooleanField(default=False, verbose_name='IS CHURCH EFFECT')),
                ('agility', models.IntegerField(default=1, verbose_name='AGILITY')),
                ('strength', models.IntegerField(default=1, verbose_name='STRENGTH')),
                ('deleted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='DELETED TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='NAME')),
                ('health', models.IntegerField(default=100, verbose_name='HP')),
                ('attack', models.IntegerField(default=1, verbose_name='ATTACK')),
                ('defence', models.IntegerField(default=1, verbose_name='ARMOR')),
                ('agility', models.IntegerField(default=1, verbose_name='AGILITY')),
                ('strength', models.IntegerField(default=1, verbose_name='STRENGTH')),
                ('lvl', models.IntegerField(default=1, verbose_name='LEVEL')),
                ('role', models.CharField(default='strength', max_length=40, verbose_name='ROLE')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('img', models.ImageField(default='', upload_to='enemy/', verbose_name='IMG')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='WEAPON NAME')),
                ('damage', models.IntegerField(verbose_name='DAMAGE+')),
                ('img', models.ImageField(upload_to='weapon', verbose_name='IMG')),
                ('balance', models.IntegerField(verbose_name='SUM')),
                ('lvl', models.IntegerField(verbose_name='LVL')),
                ('dun_lvl', models.IntegerField(verbose_name='DUNGEON LVL')),
            ],
        ),
    ]
