# Generated by Django 5.0.1 on 2024-02-11 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='ARMOR NAME')),
                ('img', models.CharField(max_length=100, verbose_name='IMG')),
                ('armor', models.IntegerField(verbose_name='AROMOR+')),
                ('balance', models.IntegerField(verbose_name='SUM')),
                ('lvl', models.IntegerField(verbose_name='LVL')),
                ('req_agility', models.IntegerField(verbose_name='REQUIRED AGILITY')),
                ('req_strength', models.IntegerField(verbose_name='REQUIRED STRENGTH')),
            ],
        ),
        migrations.CreateModel(
            name='DungeonLvl',
            fields=[
                ('lvl', models.PositiveIntegerField(primary_key=True, serialize=False, unique=True, verbose_name='DUNGEON LVL')),
                ('is_boss_killed', models.BooleanField(default=False)),
                ('min_treasure', models.IntegerField(verbose_name='MIN')),
                ('max_treasure', models.IntegerField(verbose_name='MAX')),
                ('map', models.FileField(default='maps/map1.json', upload_to='maps/')),
                ('unlock_lvl', models.PositiveIntegerField(verbose_name='LVL FOR UNLOCK BOSS')),
            ],
        ),
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='NAME')),
                ('desc', models.TextField(verbose_name='Desc')),
                ('is_positive', models.BooleanField(default=True, verbose_name='IS_POSITIVE')),
                ('is_church_ef', models.BooleanField(default=False, verbose_name='IS CHURCH EFFECT')),
                ('agility', models.IntegerField(default=1, verbose_name='AGILITY')),
                ('strength', models.IntegerField(default=1, verbose_name='STRENGTH')),
                ('deleted_time', models.DateTimeField(blank=True, default=None, null=True, verbose_name='DELETED TIME')),
            ],
        ),
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='NAME')),
                ('health', models.IntegerField(default=100, verbose_name='HP')),
                ('attack', models.IntegerField(default=1, verbose_name='ATTACK')),
                ('defence', models.IntegerField(default=1, verbose_name='ARMOR')),
                ('agility', models.IntegerField(default=1, verbose_name='AGILITY')),
                ('strength', models.IntegerField(default=1, verbose_name='STRENGTH')),
                ('lvl', models.IntegerField(default=1, verbose_name='LEVEL')),
                ('role', models.CharField(default='strength', max_length=40, verbose_name='ROLE')),
                ('img', models.CharField(max_length=50, verbose_name='IMG')),
                ('is_boss', models.BooleanField(default=False, verbose_name='IS_BOSS')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_queue', models.PositiveSmallIntegerField(verbose_name='TASK QUEUE')),
                ('name', models.CharField(max_length=50, verbose_name='TASK NAME')),
                ('desc', models.TextField(verbose_name='TASK DESK')),
                ('reward_exp', models.PositiveSmallIntegerField(verbose_name='TASK EXP')),
                ('reward_money', models.PositiveSmallIntegerField(verbose_name='TASK MONEY_REWARD')),
                ('is_current', models.BooleanField(verbose_name='IS CURRENT')),
                ('enemy_type', models.CharField(max_length=50, verbose_name='TYPE')),
                ('killed_enemies', models.PositiveIntegerField(verbose_name='KILLED')),
                ('needed_enemies', models.PositiveIntegerField(verbose_name='NEEDED')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='WEAPON NAME')),
                ('damage', models.IntegerField(verbose_name='DAMAGE+')),
                ('img', models.CharField(max_length=100, verbose_name='IMG')),
                ('balance', models.IntegerField(verbose_name='SUM')),
                ('lvl', models.IntegerField(verbose_name='LVL')),
                ('req_agility', models.IntegerField(verbose_name='REQUIRED AGILITY')),
                ('req_strength', models.IntegerField(verbose_name='REQUIRED STRENGTH')),
            ],
        ),
    ]
