# Generated by Django 5.0.1 on 2024-01-25 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='effect',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enemy',
            name='armor_equiped',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_armor_enemy', to='game.armor', verbose_name='ARMOR'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='dungeon',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='game.dungeonlvl'),
        ),
        migrations.AddField(
            model_name='effect',
            name='enemy',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effect_enemy', to='game.enemy'),
        ),
        migrations.AddField(
            model_name='weapon',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='weapon2_equiped',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon2_enemy', to='game.weapon', verbose_name='SEC WEAPON'),
        ),
        migrations.AddField(
            model_name='enemy',
            name='weapon_equiped',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipped_weapon_enemy', to='game.weapon', verbose_name='WEAPON'),
        ),
    ]
