# Generated by Django 5.0.1 on 2024-01-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_weapon_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='dungeonlvl',
            name='map',
            field=models.FileField(default='maps/map1.json', upload_to='maps/'),
        ),
    ]
