name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint_django
    - name: Install Django and other project dependencies
      run: |
        pip install -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --ignore=game/models.py --ignore=users/models.py --ignore=game/migrations --ignore=users/migrations --ignore=users/__init__.py --ignore=game/__init__.py --ignore=settings/settings.py --load-plugins pylint_django $(git ls-files '*.py') --disable=C0114,C0115,C0116,C0303,R0903,E1101

